### ISSUE TITLE
what is domain / zone the app requires

### ISSUE THREAD

**Issue by ghost** [sunfoxcz/apache-logparser#1]
more of a question.
got it to fire up, but don't understand what its looking for with the domain/zone requirements. what data does it require in these fields ?

**Comment by foxycode** [comment]
Hello, glad someone is interested. I didn't used this app for years, hope I can help.

We had specific folder structure for our hosting server. Something like `/www/domain.tld/zone` and there was apache config files for `domain.tld`. You can specify domain directory in config file. I also believe you can easily update source code to fit you own needs. For example use one directory like Apache commonly have.

Let me know if you need more help.

**Comment by ghost** [comment]
Hi,
thanks for getting back... ok I can alter that code to simple look at my /var/log/apache directory and get fancy later.

nice utility  thanks for sharing.
